# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
