# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='code',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
    ]
