# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='abc@gmail.com', max_length=126),
        ),
    ]
